---
- name: Create a Server
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Deploy a new Ubuntu VM to POC Group
      clc_server:
        name: test
        template: ubuntu-14-64
        location: NY1
        count: 1
        group: 'POC'
      register: clc
    - name: debug
      debug: var=clc.server_ids
